{% set version = "24.3" %}

package:
  name: django-filter
  version: {{ version }}

source:
  url: https://github.com/carltongibson/django-filter/archive/{{ version }}.tar.gz
  sha256: b78adb91c58d8e688daf49c1622698dce68e50b18bb989fb4f77925a826303c9

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - django >=4.2

test:
  imports:
    - django_filters
    - django_filters.rest_framework
  commands:
    - pip check
    - python -c "import django; from django.conf import settings; settings.configure(); django.setup(); import django_filters; import django_filters.rest_framework"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/carltongibson/django-filter/tree/master
  summary: Django-filter is a a generic system for filtering Django QuerySets based on user selections
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  doc_url: https://django-filter.readthedocs.io/en/latest/
  dev_url: https://github.com/carltongibson/django-filter

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
