{% set version = "23.3" %}

package:
  name: django-filter
  version: {{ version }}

source:
  url: https://github.com/carltongibson/django-filter/archive/{{ version }}.tar.gz
  sha256: 2d149f36acee64fb0d449d5bb8acd000b3c5617f4eed7d5023b242c4a7a87db3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - django >=2.2

test:
  imports:
    - django_filters
    - django_filters.rest_framework
  commands:
    - pip check
    - python -c "import django; from django.conf import settings; settings.configure(); django.setup(); import django_filters; import django_filters.rest_framework"
  requires:
    - pip

about:
  home: http://github.com/carltongibson/django-filter/tree/master
  summary: Django-filter is a a generic system for filtering Django QuerySets based on user selections
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  doc_url: https://django-filter.readthedocs.io/en/latest/
  dev_url: https://github.com/carltongibson/django-filter

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
